version: '3.8'
services:
  datjuanitagurl:
    image: datjuanitagurl/datjuanitagurl:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - 'BOT_TOKEN:$BOT_TOKEN'
      - 'CHANNEL_ID_ALERTS:$CHANNEL_ID_ALERTS'
      - 'CHANNEL_ID_FLOW:$CHANNEL_ID_FLOW'
      - 'CHANNEL_ID_GOLDEN_SWEEP:$CHANNEL_ID_GOLDEN_SWEEP'
      - 'WEBSOCKET_URL:$WEBSOCKET_URL'
      - 'WEBSOCKET_PORT:$WEBSOCKET_PORT'
      - 'FAT_VAMP:$FAT_VAMP'
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      # MongoDB errors next start without named volume
      - db-data:/data/db
    environment:
      - 'MONGO=$MONGO'
      - 'MONGO_PORT=$MONGO_PORT'
      - 'MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_USERNAME'
      - 'MONGO_INITDB_ROOT_PASSWORD:$MONGO_INITDB_ROOT_PASSWORD'
      - 'MONGO_INITDB_DATABASE:$MONGO_INITDB_DATABASE'
  badbug:
    image: datjuanitagurl/bad-bug:latest
    ports:
      - 8081:8080
    env_file:
      - .env
    environment:
      - 'MODE:$MODE'
      - 'BAD_BUG:$BAD_BUG'
      - 'BAD_BUG_USERNAME:$BAD_BUG_USERNAME'
      - 'BAD_BUG_PASSWORD:$BAD_BUG_PASSWORD'
      - 'OWL_FLOW:$OWL_FLOW'
      - 'OWL_ALERT:$OWL_ALERT'
      - 'OWL_ALERT_BTN:$OWL_ALERT_BTN'
      - 'OWL_FILTER:$OWL_FILTER'
      - 'OWL_FILTERS:$OWL_FILTERS'
      - 'OWL_FILTER_AA:$OWL_FILTER_AA'
      - 'OWL_FILTER_AAA:$OWL_FILTER_AAA'
      - 'WEBSOCKET_URL:$WEBSOCKET_URL'
      - 'WEBSOCKET_PORT:$WEBSOCKET_PORT'
    depends_on:
      - datjuanitagurl
      - mongo
volumes:
  db-data:
