version: '3.8'
services:
  datjuanitagurl:
    image: datjuanitagurl/datjuanitagurl:latest
    ports:
      - 8080:8080
    environment:
      - 'BOT_TOKEN:$BOT_TOKEN'
      - 'CHANNEL_ID_ALERTS:$CHANNEL_ID_ALERTS'
      - 'CHANNEL_ID_FLOW:$CHANNEL_FLOW'
      - 'CHANNEL_ID_GOLDEN_SWEEP:$CHANNEL_GOLDEN_SWEEP'
      - 'WEBSOCKET_URL:$WEBSOCKET_URL'
      - 'WEBSOCKET_PORT:$WEBSOCKET_PORT'

  badbug:
    image: datjuanitagurl/bad-bug:latest
    ports:
      - 8081:8081
    environment:
      - 'BAD_BUG:$BAD_BUG'
      - 'BAD_BUG_USERNAME:$BAD_BUG_USERNAME'
      - 'BAD_BUG_PASSWORD:$BAD_BUG_PASSWORD'
      - 'OWL_FLOW:$OWL_FLOW'
      - 'OWL_ALERT:$OWL_ALERT'
      - 'OWL_FILTER:$OWL_FILTER'
      - 'OWL_FILTERS:$OWL_FILTERS'
      - 'OWL_FILTER_AA:$OWL_FILTER_AA'
      - 'OWL_FILTER_AAA:$OWL_FILTER_AAA'
      - 'WEBSOCKET_URL:$WEBSOCKET_URL'
      - 'WEBSOCKET_PORT:$WEBSOCKET_PORT'
    depends_on:
      - datjuanitagurl
