version: '3.8'
services:
  datjuanitagurl:
    image: datjuanitagurl/datjuanitagurl:latest
    ports:
      - 8080:8080
    environment:
      - 'BOT_TOKEN:$BOT_TOKEN'
      - 'GUILD_ID:$GUILD_ID'

  badbug:
    image: datjuanitagurl/bad-bug:latest
    ports:
      - 8081:8081
    environment:
      - 'BAD_BUG:$BAD_BUG'
      - 'BAD_BUG_USERNAME:$BAD_BUG_USERNAME'
      - 'BAD_BUG_PASSWORD:$BAD_BUG_PASSWORD'
      - 'OWL_FILTER:$OWL_FILTER'
      - 'OWL_FILTERS:$OWL_FILTERS'
      - 'OWL_FILTER_AA:$OWL_FILTER_AA'
      - 'OWL_FILTER_AAA:$OWL_FILTER_AAA'
      - 'WEBSOCKET_URL:$WEBSOCKET_URL'
      - 'WEBSOCKET_PORT:$WEBSOCKET_PORT'
    depends_on:
      - datjuanitagurl
