version: '3.8'
services:
  datjuanitagurl:
    image: datjuanitagurl/datjuanitagurl:latest
    ports:
      - 8080:8080
    environment:
      - 'BOT_TOKEN:$BOT_TOKEN'
      - 'GUILD:$GUILD'

  badbug:
    image: datjuanitagurl/bad-bug:latest
    ports:
      - 8081:8081
    environment:
      - 'BAD_BUG:$BAD_BUG'
      - 'BAD_BUG_USERNAME:$BAD_BUG_USERNAME'
      - 'BAD_BUG_PASSWORD:$BAD_BUG_PASSWORD'
