version: '3.8'
services:
  datjuanitagurl:
    image: datjuanitagurl/datjuanitagurl:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - c:/images/:/app/images
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      # MongoDB errors next start without named volume
      - db-data:/data/db
  badbug:
    image: datjuanitagurl/bad-bug:latest
    ports:
      - 8081:8080
    env_file:
      - .env
    depends_on:
      - datjuanitagurl
      - mongo
  secretcharts:
    image: datjuanitagurl/secret-charts:latest
    ports:
      - 3001
      - 3002
    env_file:
      - .env
    volumes:
      - c:/images/:/app/images
    depends_on:
      - datjuanitagurl
      - badbug
      - mongo
volumes:
  db-data:
